give  Tue 23 Mar 14:48:31 AEDT 2021: before reformatting of commit

diff --git a/girt-add b/girt-add
--- a/girt-add
+++ b/girt-add
@@ -1,6 +1,6 @@
 #!/bin/dash
 
-if [ $# -le 1 ]
+if [ $# -lt 1 ]
 then
     echo "usage: girt-add <filenames>"
     exit 1;
@@ -9,9 +9,9 @@ if [ -d .girt ] || [ -d .girt/adds ]
 then 
     for file in $@
     do
-        if [ -f "$file" ] &&  echo "$file" | egrep -q ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
+        if [ -f "$file" ] || [ -f .girt/adds/"$file" ] # &&  echo "$file" | egrep -q ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
         then 
-            cp "$file" ".girt/adds";
+            :
         else
             echo "girt-add: error: can not open '"$file"'";
             exit 1;
@@ -21,4 +21,20 @@ else
     echo "girt-add: error: girt repository directory .girt not found"
     exit 1;
 fi
+
+for file in $@
+do
+    # adding the file if it exists in the cwd
+    if [ -f "$file" ] # &&  echo "$file" | egrep -q ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
+    then 
+        cp "$file" ".girt/adds";
+    # removing a file if it is not in cwd but in .girt/adds
+    elif [ -f .girt/adds/"$file" ] 
+    then
+        rm .girt/adds/"$file";
+    else
+        echo "girt-add: error: can not open '"$file"'";
+        exit 1;
+    fi
+done
 exit 0;
diff --git a/girt-rm b/girt-rm
--- a/girt-rm
+++ b/girt-rm
@@ -37,32 +37,36 @@ do
     
     if [ -f .girt/adds/"$file" ]
     then
-        # checking for unsaved changes in .girt/adds
-        diff -s ".girt/adds/$file" ".girt/commit_"$prev_commit_no"/"$file_name"" >/dev/null 2>/dev/null;
-        if [ $? -eq 0 ] #same file content
-        then 
+        if [ "$1" = "--cached" ] || [ "$2" = "--cached" ] ||  [ "$1" = "--force" ] || [ "$2" = "--force" ]  
+        then
             :
-        else #1 or 2 so different file content or error like file not found
-            echo "girt-rm: error: '"$file"' has staged changes in the index"; #adds vs commit
-            exit 0;
-        fi
+        else #girt-rm: error: 'a' in the repository is different to the working file
+            # checking for unsaved changes in .girt/adds (#adds vs commit)
+            diff -s ".girt/adds/$file" ".girt/commit_"$prev_commit_no"/"$file"" >/dev/null 2>/dev/null;
+            if [ $? -eq 0 ] #same file content
+            then 
+                :
+            else #1 or 2 so different file content or error like file not found
+                echo "girt-rm: error: '"$file"' has staged changes in the index";
+                exit 0;
+            fi
 
-        # checking for unsaved changes in cwd
-        diff -s "$file" ".girt/"$prev_commit_no"/"$file_name"" >/dev/null 2>/dev/null;
-        if [ $? -eq 0 ] #same file content
-        then 
-            :
-        else #1 or 2 so different file content or error like file not found
-            echo "girt-rm: error: '"$file"' in index is different to both to the working file and the repository"; #cwd vs commit
-            exit 0;
+            # checking for unsaved changes in cwd  (#cwd vs commit)
+            diff -s "./"$file"" ".girt/commit_"$prev_commit_no"/"$file"" >/dev/null 2>/dev/null;
+            if [ $? -eq 0 ] #same file content
+            then 
+                :
+            else #1 or 2 so different file content or error like file not found
+                echo "girt-rm: error: '"$file"' in index is different to both to the working file and the repository";
+                exit 0;
+            fi
         fi
-
         # remove file
-        echo "removing ./girt/adds/"$file"";
+        #echo "removing ./girt/adds/"$file"";
         rm .girt/adds/"$file";
-    elif [ "$file" != '--force' ] || [ "$file" != '--cached' ] 
+    elif [ "$file" != '--force' ] && [ "$file" != '--cached' ] 
     then
-        echo 'girt-rm: error: '"$file"' is not in the girt repository';    
+        echo "girt-rm: error: '"$file"' is not in the girt repository";    
         exit 1;
     fi
     
@@ -74,7 +78,7 @@ do
     else
         if [ -f ./"$file" ]
         then
-            echo "removing ./"$file"";
+            #echo "removing ./"$file"";
             rm ./"$file";
         fi
     fi
