give  Wed 24 Mar 21:50:49 AEDT 2021: coded branch and checkout but with bugs

diff --git a/girt-branch b/girt-branch
--- a/girt-branch
+++ b/girt-branch
@@ -1,5 +1,12 @@
 #!/bin/dash
 
+if [ -d .girt ]
+then :
+else 
+    echo "girt-commit: error: girt repository directory .girt not found"
+    exit 1;
+fi
+
 if [ -d .girt/commit_0 ]
 then
     :
@@ -26,12 +33,12 @@ then
     echo "error girt-branch: error: branch name required";
     exit 1;
 
-elif [ $# -eq 1 ] && $( echo "$1" | egrep '^-.*' )
+elif [ $# -eq 1 ] && echo "$1" | egrep -q '^-.*'
 then 
     echo "usage: girt-branch [-d] <branch>";
     exit 1;
 
-elif [ $# -eq 1 ] && $( echo "$1" | egrep '^[^a-zA-Z].*' )
+elif [ $# -eq 1 ] && echo "$1" | egrep -q '^[^a-zA-Z].*'
 then 
     echo "girt-branch: error: invalid branch name '"$1"'";
     exit 1;
@@ -39,28 +46,39 @@ then
 elif [ $# -eq 1 ]
 then 
     #create that branch
-    if [ -d .girt/branches/"$1" ]
+    if [ -d .girt/branches/"$1" ] || [ "$1" = "master" ]
     then 
         echo "girt-branch: error: branch '"$1"' already exists";
         exit 1;
     else
-        #mkdir .girt/branches/"$1";
-        echo "making branch "$1"";
+        mkdir .girt/branches/"$1";
+        #echo "making branch "$1"";
+        for file in *
+        do
+            if [ -f "$file" ]
+            then
+                cp "$file" .girt/branches/"$1"/"$file";
+            fi
+        done
         #copy of all files into branch?
     fi
-elif [ $# -eq 2 ] && [ "$1" = "-d" ] && $( echo "$1" | egrep '^[a-zA-Z].*' )
+elif [ $# -eq 2 ] && [ "$1" = "-d" ] &&  echo "$2" | egrep -q '^[a-zA-Z].*'
 then
     #delete that branch
-    if [ -d .girt/branches/"$1" ]
+    if [ -d .girt/branches/"$2" ]
     then 
-        rm -r .girt/branches/"$1";
+        rm -r .girt/branches/"$2";
+    elif [ "$2" = "master" ]
+    then
+        echo "girt-branch: error: can not delete branch 'master'"
+        exit 1;
     else
-        echo "girt-branch: error: branch '"$1"' doesn't exist";
+        echo "girt-branch: error: branch '"$2"' doesn't exist";
         exit 1;
     fi
-elif [ $# -eq 2 ] && [ "$1" = "-d" ] && $( echo "$1" | egrep '^[^a-zA-Z].*' )
+elif [ $# -eq 2 ] && [ "$1" = "-d" ] && echo "$2" | egrep -q '^[^a-zA-Z].*'
 then 
-    echo "girt-branch: error: invalid branch name '"$1"'";
+    echo "girt-branch: error: invalid branch name '"$2"'";
     exit 1;
 
 else
