give  Mon 22 Mar 22:40:26 AEDT 2021: updated commit and started rrm

diff --git a/girt-commit b/girt-commit
--- a/girt-commit
+++ b/girt-commit
@@ -1,5 +1,12 @@
 #!/bin/dash
 
+if [ -d .girt ]
+then :
+else 
+    echo "girt-commit: error: girt repository directory .girt not found"
+    exit 1;
+fi
+
 # error cases
 if [ $# -ne 2 ] && [ $# -ne 3 ]
 then 
@@ -77,6 +84,17 @@ fi
 
 #creating a commit sub directory
 mkdir ".girt/commit_"$commit_no"";
+
+# sync adds directory with cwd except files not added before
+if [ "$1" = "-a" ]
+then 
+    for add_files in .girt/adds/*
+    do
+        f_name=$(echo "$add_files" | sed 's/.girt\/adds\//''/g');
+        #echo "$f_name syncing to adds";
+        cp "$f_name" ".girt/adds";
+    done
+fi
 
 #copies files from adds into commmit sub directory
 for file in .girt/adds/*
diff --git a/girt-log b/girt-log
--- a/girt-log
+++ b/girt-log
@@ -1,5 +1,12 @@
 #!/bin/dash
 
+if [ -d .girt ]
+then :
+else 
+    echo "girt-log: error: girt repository directory .girt not found"
+    exit 1;
+fi
+
 for directories in .girt/*
 do
     if echo "$directories" | egrep -q '^.girt/commit_.$' && [ -d "$directories" ]
diff --git a/girt-show b/girt-show
--- a/girt-show
+++ b/girt-show
@@ -1,5 +1,12 @@
 #!/bin/dash
 
+if [ -d .girt ]
+then :
+else 
+    echo "girt-show: error: girt repository directory .girt not found"
+    exit 1;
+fi
+
 if [ $# -ne 1 ]
 then
     echo "usage: girt-show <commit>:<filename>"
